name: HTML Lint & Deploy Pages

on:
  push:
    branches: [main, master]

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v0.2.0
        with:
          files: .
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
